### ISSUE TITLE
pedump.me site is down

### ISSUE THREAD

**Issue by FuccDucc** [zed-0xff/pedump#16]
Your site is inaccessible since a couple of days.. it shows **ERR_CONNECTION_REFUSED** from multiple network locations i tried at.

Are you abandoning your site, or is this a hosting problem that you didn't notice yet? I hope it can be fixed soon, as your site is useful. @zed-0xff

**Comment by zed-0xff** [comment]
fixed

**Comment by FuccDucc** [comment]
I propose to use this issue on the tracker to notify zed (with a tag) of any future outages of the site, considering that it has reliability issues and goes down regularly

**Comment by FuccDucc** [comment]
@zed-0xff The pedump.me site is down (has been down for a couple days if im not wrong), please fix again ; p

**Comment by FuccDucc** [comment]
@zed-0xff Has pedump.me been abandoned?
