### ISSUE TITLE
pedump.me not working since over a year

### ISSUE THREAD

**Issue by faekyu** [zed-0xff/pedump#43]
Hello,

For over a year, probably much longer, the site [https://pedump.me/](https://pedump.me/) hasn't been functioning. It is inoperable because as soon you try to upload a file for analysis, it returns "405 Not Allowed" http code from nginx, without performing its functions. There is no uploading or analysing files, then the site serves no purpose.

Due to the history of this site having outages or blocking technical issues, the situation and how long it's been lasting made me believe it was simply an abandoned site, project/not really cared about anymore. So until now i didnt bother reporting it, expecting no result if that were the case, but i got reminded of how useful this site was as utility so im here putting that little bit of effort in after all.

Also, isn't this a waste of your hosting costs? To keep an inoperable site online, i mean.. maybe you even felt as if the site was simply not popular anymore, while in reality users were leaving for good due to the broken state. You can still salvage that. Btw, i suspect the time this situation exists even crosses the 2 years mark.

Any comment @zed-0xff ?

**Comment by zed-0xff** [comment]
fixed. thx 4 writing this.

**Comment by zed-0xff** [comment]
fixed

**Comment by zed-0xff** [comment]
revived
