### ISSUE TITLE
Authenticode signing check

### ISSUE THREAD

**Issue by tangentsoft** [zed-0xff/pedump#45]
If I have a random EXE downloaded from the Internet, I would like to get an indication that it is signed with Authenticode. Actually checking the signature is a bonus. A simple yes/no signature existence report would suffice for my immediate purposes.

I don't see anything in the docs about whether `pedump` can do this, nor does searching the tool's output indicate that it does have this as an undocumented feature.

I'm aware of Windows tools that can do this, but I need to do this from the command line on another OS.

**Comment by tangentsoft** [comment]
Thanks for the `--security` tip. I don't know how I missed it.

As for verification of the CA chain, all modern OSes have CA roots and cert chains on them somewhere, and libraries like OpenSSL know how to tap into them and use them.

**Comment by zed-0xff** [comment]
For HTTPS they are.
But I'm pretty sure that executable signing has different certs and their sources.
